In [1]:
print("Hello World")

Hello World


# Variable in python 3

In [3]:
x=5
y='Hello'

print('X is {} and says "{}"'.format(x,y))

X is 5 and says "Hello"


In [5]:
#Get all keyword
import keyword
print(keyword.kwlist)

print('Number of keyword = ',len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
Number of keyword =  35


In [ ]:
students_grade = ['A','A','B','C','B','C']


In [8]:
students_grade=set(students_grade)
print(set(students_grade))


{'C', 'A', 'B'}


# Numpy in Python

In [2]:
 import numpy as np

In [13]:
a=np.array([1,2,3,4,5,6])

In [27]:

b=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])

print(b)
print(b.dtype)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
int64


In [29]:
b.ndim

2

In [32]:
print(b.shape,type(b))


(6, 6) <class 'numpy.ndarray'>


In [37]:
print(np.arange(50))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [39]:
c=range(10000)
%timeit [i**3 for i in c]


2.49 ms ± 30.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
cc=np.arange(1000)
cc


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [32]:
import numpy as np

b=np.arange(27).reshape(3,3,3)

print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [33]:
b.shape

(3, 3, 3)

In [34]:
b[[1,2,2]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
b[[2,0]]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [36]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a[2]

array([7, 8, 9])

In [39]:
a[1,2]

6

In [49]:
bbb=a[(a>2)&(a<9)]

In [50]:
bbb.reshape(2,-1)

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
w=bb<2

In [54]:
w.reshape(2,3)

array([[False, False, False],
       [False, False, False]])

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

b=a
np.shares_memory(a,b)

True

# Panda and Dataframe

In [1]:
import pandas as pd
import random

import numpy as np


print("Hello")
a = pd.Series([1, 2, 3], [4, 5, 6])

print(a)

temp = np.random.randint(low=20, high=100, size=[20, ])
name = np.random.choice(['Shimul', 'Mahid', 'Zahid', 'Nitto', 'Farhad'], 20)

randoms = np.random.choice([10, 11, 12, 13, 14, 34], 20)

dd = list(zip(temp, randoms, name))

dataframe = pd.DataFrame(data=dd, columns=["Marks",'Age','Name'])
print(dataframe)


df = pd.DataFrame({"Marks": temp, 'Age': randoms, 'Name': name})

print(df)

print(df['Marks'].describe())

print(df.values)

Hello
4    1
5    2
6    3
dtype: int64
    Marks  Age    Name
0      68   10  Farhad
1      56   10   Mahid
2      77   14  Farhad
3      40   10  Farhad
4      29   13   Nitto
5      42   13   Zahid
6      71   13   Nitto
7      77   34   Nitto
8      26   13  Shimul
9      38   10  Shimul
10     57   14   Nitto
11     95   14  Shimul
12     31   12   Zahid
13     86   34   Mahid
14     50   13   Nitto
15     72   12   Nitto
16     64   13  Farhad
17     78   10   Mahid
18     37   14   Mahid
19     84   34  Farhad
    Marks  Age    Name
0      68   10  Farhad
1      56   10   Mahid
2      77   14  Farhad
3      40   10  Farhad
4      29   13   Nitto
5      42   13   Zahid
6      71   13   Nitto
7      77   34   Nitto
8      26   13  Shimul
9      38   10  Shimul
10     57   14   Nitto
11     95   14  Shimul
12     31   12   Zahid
13     86   34   Mahid
14     50   13   Nitto
15     72   12   Nitto
16     64   13  Farhad
17     78   10   Mahid
18     37   14   Mahid
19     84   34  F

# Control Flow Basics if elif else and  For Loops




In [2]:
import pandas as pd
import random
a = 1
while a != 0:
    a = int(input('Enter the marks to check Grade : '))
    if a == 0:
        break

    if a < 40:
        print('Fail')
    elif a >= 80:
        print('A+')
    elif a >= 70:
        print("A")

    elif a >= 60:
        print("B")
    elif a >= 50:
        print("C")
print('You exit the process')

a = [1, 2, 3, 4, 5, 6]

for i in a:
    if i==6:
        print(i)
        break
    print(i,end='---')


for item,letter in enumerate("Shimul"):
    print('At {} index {} is placed'.format(item,letter))


a=list(enumerate('Shimul'))

my_list1=a[::-1]

my_list2=a[0::]
mm=['','','','','']
zipper=zip(my_list1,mm,my_list2)


df=pd.DataFrame(data=zipper,columns=['Inverse Letters','            ',      'Normal Letters'])

print(df)




my_list = []
for letter in 'Something':

    my_list.append(letter)
print(my_list)

my_list1 = [letter1 for letter1 in "Something"]

print(my_list1)

ff = [x for x in range(0, 11) if x % 2 == 0]
print(ff)

ms = []
for x in 'Shimul':
    str(ms.append(ord(x)))
for i in ms:
    print(i)

Enter the marks to check Grade : 85
A+
Enter the marks to check Grade : 0
You exit the process
1---2---3---4---5---6
At 0 index S is placed
At 1 index h is placed
At 2 index i is placed
At 3 index m is placed
At 4 index u is placed
At 5 index l is placed
  Inverse Letters              Normal Letters
0          (5, l)                      (0, S)
1          (4, u)                      (1, h)
2          (3, m)                      (2, i)
3          (2, i)                      (3, m)
4          (1, h)                      (4, u)
['S', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g']
['S', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g']
[0, 2, 4, 6, 8, 10]
83
104
105
109
117
108


# Lambda Expressions, Map, and Filter

In [3]:

def square(number):
    return number ** 2


my_num_List = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

new_list = list(map(square, my_num_List))
print(new_list)


def splicer(my_string):
    if len(my_string) % 2 != 0:
        return my_string
    else:
        return my_string[0]


my_string = ['Helwlo', 'Shimul_']

print(list(map(splicer, my_string)))


def even_checker(nums):
    """
    THis is the thing that will help you in your near future
    """
    return nums % 2 != 0

print(list(filter(even_checker, my_num_List)))

print(list(map(lambda x: x ** 2, my_num_List)))


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
['H', 'Shimul_']
[1, 3, 5, 7, 9, 11, 13]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
